"""baseline v2 schema

Revision ID: a51626c6d73c
Revises: 
Create Date: 2026-07-03 10:18:47.673463
"""
from alembic import op
import sqlalchemy as sa


revision = 'a51626c6d73c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity_type', sa.String(length=60), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lon', sa.Float(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=True)
    op.create_table('data_source_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_key', sa.String(length=60), nullable=False),
    sa.Column('provider_name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_key')
    )
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_updated', sa.Integer(), nullable=False),
    sa.Column('rows_skipped', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_started_at'), 'ingestion_runs', ['started_at'], unique=False)
    op.create_table('intervention_catalog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit_cost_min_inr_lakh', sa.Float(), nullable=False),
    sa.Column('unit_cost_max_inr_lakh', sa.Float(), nullable=False),
    sa.Column('cooling_impact_min_c', sa.Float(), nullable=False),
    sa.Column('cooling_impact_max_c', sa.Float(), nullable=False),
    sa.Column('risk_reduction_min_pts', sa.Float(), nullable=False),
    sa.Column('risk_reduction_max_pts', sa.Float(), nullable=False),
    sa.Column('timeline_weeks_min', sa.Integer(), nullable=False),
    sa.Column('timeline_weeks_max', sa.Integer(), nullable=False),
    sa.Column('assumptions', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('scenario_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('cool_roof_coverage', sa.Float(), nullable=False),
    sa.Column('tree_cover_gain', sa.Float(), nullable=False),
    sa.Column('shade_units', sa.Integer(), nullable=False),
    sa.Column('budget_lakh', sa.Float(), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=False),
    sa.Column('projected_score', sa.Float(), nullable=False),
    sa.Column('projected_lst_c', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_runs_ward_id'), 'scenario_runs', ['ward_id'], unique=False)
    op.create_table('wards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('area_km2', sa.Float(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=False),
    sa.Column('centroid_lon', sa.Float(), nullable=False),
    sa.Column('map_x', sa.Float(), nullable=False),
    sa.Column('map_y', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'name', name='uq_ward_city_name')
    )
    op.create_index(op.f('ix_wards_city_id'), 'wards', ['city_id'], unique=False)
    op.create_index(op.f('ix_wards_name'), 'wards', ['name'], unique=False)
    op.create_table('intervention_simulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('budget_inr_lakh', sa.Float(), nullable=False),
    sa.Column('roof_treatment_pct', sa.Float(), nullable=False),
    sa.Column('tree_canopy_target_pct', sa.Float(), nullable=False),
    sa.Column('shade_structures', sa.Integer(), nullable=False),
    sa.Column('infra_focus', sa.String(length=60), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=False),
    sa.Column('projected_score', sa.Float(), nullable=False),
    sa.Column('risk_reduction_pts', sa.Float(), nullable=False),
    sa.Column('allocations', sa.JSON(), nullable=False),
    sa.Column('assumptions', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_simulations_created_at'), 'intervention_simulations', ['created_at'], unique=False)
    op.create_index(op.f('ix_intervention_simulations_ward_id'), 'intervention_simulations', ['ward_id'], unique=False)
    op.create_table('satellite_scenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('scene_id', sa.String(length=200), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=40), nullable=False),
    sa.Column('geometry_coverage', sa.Text(), nullable=True),
    sa.Column('lst_c', sa.Float(), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('ndbi', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_satellite_scenes_city_id'), 'satellite_scenes', ['city_id'], unique=False)
    op.create_index(op.f('ix_satellite_scenes_observed_at'), 'satellite_scenes', ['observed_at'], unique=False)
    op.create_index(op.f('ix_satellite_scenes_ward_id'), 'satellite_scenes', ['ward_id'], unique=False)
    op.create_table('ward_feature_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('lst_c', sa.Float(), nullable=True),
    sa.Column('air_temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('ndvi', sa.Float(), nullable=True),
    sa.Column('ndbi', sa.Float(), nullable=True),
    sa.Column('built_up_pct', sa.Float(), nullable=True),
    sa.Column('road_density_km_km2', sa.Float(), nullable=True),
    sa.Column('population_density', sa.Float(), nullable=True),
    sa.Column('vulnerability_index', sa.Float(), nullable=True),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_feature_snapshots_created_at'), 'ward_feature_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_ward_feature_snapshots_observed_at'), 'ward_feature_snapshots', ['observed_at'], unique=False)
    op.create_index(op.f('ix_ward_feature_snapshots_ward_id'), 'ward_feature_snapshots', ['ward_id'], unique=False)
    op.create_table('ward_geometries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('geometry_geojson', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('is_demo_geometry', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ward_geometries_ward_id'), 'ward_geometries', ['ward_id'], unique=True)
    op.create_table('weather_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('air_temp_c', sa.Float(), nullable=True),
    sa.Column('apparent_temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('wind_speed_mps', sa.Float(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('is_forecast', sa.Boolean(), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weather_observations_city_id'), 'weather_observations', ['city_id'], unique=False)
    op.create_index(op.f('ix_weather_observations_observed_at'), 'weather_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_weather_observations_ward_id'), 'weather_observations', ['ward_id'], unique=False)
    op.create_table('heat_risk_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ward_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('top_factors', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('missing_data_warnings', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ward_feature_snapshots.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_heat_risk_scores_computed_at'), 'heat_risk_scores', ['computed_at'], unique=False)
    op.create_index(op.f('ix_heat_risk_scores_ward_id'), 'heat_risk_scores', ['ward_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_heat_risk_scores_ward_id'), table_name='heat_risk_scores')
    op.drop_index(op.f('ix_heat_risk_scores_computed_at'), table_name='heat_risk_scores')
    op.drop_table('heat_risk_scores')
    op.drop_index(op.f('ix_weather_observations_ward_id'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_observed_at'), table_name='weather_observations')
    op.drop_index(op.f('ix_weather_observations_city_id'), table_name='weather_observations')
    op.drop_table('weather_observations')
    op.drop_index(op.f('ix_ward_geometries_ward_id'), table_name='ward_geometries')
    op.drop_table('ward_geometries')
    op.drop_index(op.f('ix_ward_feature_snapshots_ward_id'), table_name='ward_feature_snapshots')
    op.drop_index(op.f('ix_ward_feature_snapshots_observed_at'), table_name='ward_feature_snapshots')
    op.drop_index(op.f('ix_ward_feature_snapshots_created_at'), table_name='ward_feature_snapshots')
    op.drop_table('ward_feature_snapshots')
    op.drop_index(op.f('ix_satellite_scenes_ward_id'), table_name='satellite_scenes')
    op.drop_index(op.f('ix_satellite_scenes_observed_at'), table_name='satellite_scenes')
    op.drop_index(op.f('ix_satellite_scenes_city_id'), table_name='satellite_scenes')
    op.drop_table('satellite_scenes')
    op.drop_index(op.f('ix_intervention_simulations_ward_id'), table_name='intervention_simulations')
    op.drop_index(op.f('ix_intervention_simulations_created_at'), table_name='intervention_simulations')
    op.drop_table('intervention_simulations')
    op.drop_index(op.f('ix_wards_name'), table_name='wards')
    op.drop_index(op.f('ix_wards_city_id'), table_name='wards')
    op.drop_table('wards')
    op.drop_index(op.f('ix_scenario_runs_ward_id'), table_name='scenario_runs')
    op.drop_table('scenario_runs')
    op.drop_table('intervention_catalog')
    op.drop_index(op.f('ix_ingestion_runs_started_at'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_table('data_source_status')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
